[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = "0.8.0"
evm_version = "cancun"
# remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/", "v2-core/=lib/v2-core/",
#     "v2-periphery/=lib/v2-periphery/"]
remappings = [
    '@uniswap/v2-core/=lib/v2-core/',
    '@uniswap/v2-periphery/=lib/v2-periphery/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'forge-std/=lib/forge-std/src/',
    'prb-math/=lib/prb-math/src/',
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
